### ISSUE TITLE
화면 기본 레이아웃

### ISSUE THREAD

**Issue by kim-choongwan** [kim-choongwan/sql-builder#6]
- [ ] 레이아웃 최상위 컴포넌트를 만든다.
- [ ] 탑 사이즈 고정.
- [ ] 좌측메뉴와 우측메뉴 사이즈는 고정(임시)
- [ ] 사이즈는 속성으로 설정한다.
- [ ] 레이어 개별 영역에는 무언가 (동적으로) 들어 갈 수 있는 구조여야 한다.
- [ ] main 태그를 사용하는 영역은 sql을 조립하는 공간으로 함
- [ ] resizin 컴포넌트 명을 splitter로 변경
- [ ] 전역 이벤트를 이용하지 말고 해당 컴포넌트에 대한 이벤트를 추가 및 삭제
- [ ] wrap 이 뒤에 붙은 것은 명칭에서 다 제거 할 것.

**Comment by YunWonYong** [comment]
1.main 태그를 이용한 영역은 sql을 조립하는 공간명으로 함.
2.상단 top은 고정이어야 함.
3.resizing 컴포넌트의 명을 splitter로 변경
4.전역이벤트를 이용하지 않고 해당 컴포넌트에 이벤트를 주입 및 삭제
5.자바스크립트로 해당 컴포넌트에 값을 수정하지 말고 이벤트를 통해 정보를 전달 할 것
